services:
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
